class AbortException(Exception):...
class HandlerError(Exception):...
class ParameterError(Exception):...
class SubdomainError(Exception):...
class UrlError(Exception):...
class UrlDuplicateError(Exception):...
