site_name: Heaven Web Framework (Routerling)
site_url: https://rayattack.github.io/heaven

site_description: Web Application Framework
site_author: Raymond Ortserga

repo_name: rayattack/heaven
repo_url: https://www.github.com/rayattack/heaven

theme:
  name: 'material'
  palette:
    primary: black
  include_search_page: false
  feature:
    tabs: true
  logo: 'images/logo.png'

plugins:
  - search
  - tags
  - termynal
  - minify:
      minify_html: true

nav:
  - Heaven v1.3.1: index.md
  - Intro: index.md
  - Min 01-02&colon; The Beginning: quickstart.md
  - Min 03-04&colon; The Command Line: cli.md
  - Min 05-06&colon; The Router: router.md
  - Min 07-08&colon; Subdomains: subdomains.md
  - Min 09-10&colon; The Request: request.md
  - Min 11-12&colon; The Response: response.md
  - Min 13-14&colon; The Context: context.md
  - Min 15-16&colon; HTML & Assets: html.md
  - Min 17-18&colon; Interceptors: hooks.md
  - Min 19-20&colon; Schemas: schema.md
  - Min 21-22&colon; API Docs: openapi.md
  - Min 23-24&colon; Testing (Earth): earth.md
  - Min 25-26&colon; Background Tasks: daemons.md
  - Min 27-28&colon; Security & Plugins: security.md
  - Min 29-30&colon; Deployment: deployment.md
  - That's it&colon; Congrats: congrats.md
  - Appendix&colon; Going to Production: production.md
  - Appendix&colon; Plugins System: plugins.md
  - Appendix&colon; Plugin Marketplace: marketplace.md
  - Appendix&colon; API Reference: api.md
  - Appendix&colon; Examples: examples.md

extra_css:
  - 'css/custom.css'
  - 'css/termynal.css'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - js/termynal.js
  - js/custom.js
