site_name: Heaven Web Framework (Routerling)
site_url: https://rayattack.github.io/heaven

site_description: Web Application Framework
site_author: Raymond Ortserga

repo_name: rayattack/heaven
repo_url: https://www.github.com/rayattack/heaven

theme:
  name: 'material'
  palette:
    primary: black
  include_search_page: false
  feature:
    tabs: true
  logo: 'images/logo.png'

plugins:
  - search
  - tags
  - termynal
  - minify:
      minify_html: true

nav:
  - Heaven v1.3.6: index.md
  - Intro: index.md
  - The Beginning: quickstart.md
  - The Command Line: cli.md
  - The Router: router.md
  - Subdomains: subdomains.md
  - The Request: request.md
  - The Response: response.md
  - The Context: context.md
  - HTML & Assets: html.md
  - Interceptors: hooks.md
  - Schemas: schema.md
  - API Docs: openapi.md
  - Testing (Earth): earth.md
  - Background Tasks: daemons.md
  - Security & Plugins: security.md
  - Deployment: deployment.md
  - Congrats: congrats.md
  - Appendix&colon; Going to Production: production.md
  - Appendix&colon; Plugins System: plugins.md
  - Appendix&colon; Plugin Marketplace: marketplace.md
  - Appendix&colon; API Reference: api.md
  - Appendix&colon; Examples: examples.md

extra_css:
  - 'css/custom.css'
  - 'css/termynal.css'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - js/termynal.js
  - js/custom.js
